default: &default
  host: <%= ENV['POSTGRES_1_PORT_5432_TCP_ADDR'] %>
  adapter: postgresql
  user: postgres
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hn-monitor-dev

test:
  <<: *default
  database: hn-monitor-test
